<?php

use Drupal\Core\Controller\ControllerBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Form alter module
 *
 * @param [type] $form
 * @param FormStateInterFace $form_state
 * @param [type] $form_id
 * @return void
 */
function first_module_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
  if ($form_id = 'user_login_form') {
    // form title header
    $form['#title'] = t('Login with Company info');
    // form username field
    $form['name']['#title'] = t('Company username');
    $form['name']['#attributes']['placeholder'] = t('Company username');
    // form password field
    $form['pass']['#title'] = t('Company password');
    $form['pass']['#attributes']['placeholder'] = t('Company password');
  }
};

/**
 * Hook to pass variable form module to theme
 *
 * @param [type] $variables
 * @return void
 */
function first_module_preprocess_page(&$variables) {
  $variables['first_module_variables'] = 'My first D11 site';
};

/**
 * help hook for the first module
 *
 * @param [type] $route_name
 * @param RouteMatchInterface $route_match
 * @return void
 */
function first_module_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page':
     $output = <<<HTML
        <h3>About</h3>
        <p>This is help for first module</p>
      HTML;
      return $output;

    default:
  }
}